mixed-port: 7890
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - name: "6666.tw"
    type: http
    server: 66.tw.cn
    port: 2800
    username: user
    password: benq123
  # tls: true # https
  # skip-cert-verify: true
proxy-groups:
rules:
